[tools]
antigravity-cli = "latest"
aube = "latest"
bun = "latest"
cargo-binstall = "latest"
"cargo:ast-grep" = "latest"
cursor-agent = "latest"
difftastic = "latest"
"cargo:du-dust" = { version = "latest", default-features = false }
"cargo:jinja-lsp" = "latest"
"cargo:selene" = "latest"
elixir-ls = "latest"
eza = "latest"
fastfetch = "latest"
fd = "latest"
fzf = "latest"
git-lfs = "latest"
github-cli = "latest"
"github:alltuner/mise-completions-sync" = "latest"
"github:anthropics/claude-code" = "latest"
"github:boyter/scc" = "latest"
"github:lucasgelfond/zerobrew" = { version = "latest", matching = "zb-", rename_exe = "zb" }
"github:microsoft/vscode-js-debug" = { version = "latest", asset_pattern = "js-debug-dap-*.tar.gz" }
go = "latest"
"go:github.com/docker/docker-language-server/cmd/docker-language-server" = "latest"
hadolint = "latest"
hunkdiff = "latest"
lazydocker = "latest"
lazygit = "latest"
lua = "5.1"
lua-language-server = "latest"
marksman = "latest"
neovim = "latest"
node = "latest"
"npm:@crafter/trx" = "latest"
"npm:@earendil-works/pi-coding-agent" = "latest"
"npm:@llamaindex/liteparse" = "latest"
"npm:@mermaid-js/mermaid-cli" = "latest"
"npm:@tailwindcss/language-server" = "latest"
"npm:@vtsls/language-server" = "latest"
"npm:agent-browser" = "latest"
"npm:defuddle" = "latest"
"npm:markdown-toc" = "latest"
"npm:neovim" = "latest"
"npm:pm2" = "latest"
"npm:rustywind" = "latest"
"npm:skills" = "latest"
"npm:stylelint" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"npm:yaml-language-server" = "latest"
opam = { version = "latest", asset_pattern = "opam-*-{gnu_arch}-{os}" }
oxfmt = "latest"
oxlint = "latest"
"pipx:djlint" = "latest"
"pipx:git+https://github.com/tudorandrei/kokoro-tts.git" = "main"
"pipx:huggingface_hub" = "latest"
"pipx:zotero-cli" = "latest"
pnpm = "latest"
ripgrep = "latest"
ruff = "latest"
rumdl = "latest"
rust = "latest"
rust-analyzer = "latest"
shfmt = "latest"
starship = "latest"
stylua = "latest"
taplo = "latest"
tree-sitter = "latest"
ty = "latest"
uv = "latest"
worktrunk = "latest"
yamlfmt = "latest"
yt-dlp = "latest"
zoxide = "latest"
"github:coollabsio/coolify-cli" = "latest"
ast-grep = "latest"
herdr = "latest"
codex = "latest"
"npm:ctx7" = "latest"
"npm:hyperframes" = "latest"
pandoc = "latest"
"pipx:git-filter-repo" = "latest"
typst = "latest"
"aqua:cloudflare/cloudflared" = "latest"
"github:TudorAndrei/ste-cli" = "0.8.2"
"npm:markdownlint-cli" = "0.49.1"

[settings]
auto_update = true
npm.package_manager = "aube"
experimental = true
minimum_release_age = "0s"

[settings.cargo]
binstall = true

[hooks]
postinstall = "misecompsync --shell zsh"
