[character]
error_symbol = "[Œª](bold #ff5555)"
success_symbol = "[Œª](bold #50fa7b)"

[hostname]
style = "bold #bd93f9"

[username]
format = '\[[$user]($style)\]'
style_user = "bold #8be9fd"

[cmd_duration]
format = '\[[‚è± $duration]($style)\]'
style = "bold #f1fa8c"

# Disable the package module, hiding it from the prompt completely
[battery]
disabled = true

[directory]
truncation_length = 5
style = "bold #50fa7b"
format = "[$path]($style)[$lock_symbol]($lock_style) "

[git_branch]
symbol = "Ôêò "
truncation_length = 10
truncation_symbol = ""
style = "bold #ff79c6"
format = '\[[$symbol$branch]($style)\]'

[git_commit]
commit_hash_length = 4
tag_symbol = "üîñ "


[git_status]
ahead = "‚á°${count}"
diverged = "‚áï‚á°${ahead_count}‚á£${behind_count}"
behind = "‚á£${count}"
format = '([\[$all_status$ahead_behind\]]($style))'
style = "bold #ff5555"


[custom.git_scope]
command = '''
printf "%s" \
  "$(if [ -n "$GIT_AUTHOR_NAME" ]; then echo "$GIT_AUTHOR_NAME"; else git config user.name; fi)"
'''
description = 'The currently configured Git user.{email,name}'
format = ' as [$output]($style) '
shell = ["zsh"]
style = 'blue bold'
when = 'git rev-parse --is-inside-work-tree'
